economy:
  ex: 8000
  levels:
    grad:
      ex: 1400
    ug:
      ex: 6600
  qa: 1000
  types:
    判断题: 0
    填空题: 0
    案例分析题: 0
    简答题: 0
    论述题: 0
    选择题: 0
finance:
  ex: 35100
  levels:
    grad:
      ex: 16300
    ug:
      ex: 18800
  qa: 5000
  types:
    判断题: 0
    填空题: 0
    案例分析题: 0
    简答题: 0
    论述题: 0
    选择题: 0
intl:
  ex: 17800
  levels:
    grad:
      ex: 8500
    ug:
      ex: 9300
  qa: 1500
  types:
    判断题: 0
    填空题: 0
    案例分析题: 0
    简答题: 0
    论述题: 0
    选择题: 0
mgmt:
  ex: 11100
  levels:
    grad:
      ex: 4600
    ug:
      ex: 6500
  qa: 2500
  types:
    判断题: 0
    填空题: 0
    案例分析题: 0
    简答题: 0
    论述题: 0
    选择题: 0
tax:
  ex: 15400
  levels:
    grad:
      ex: 7200
    ug:
      ex: 8200
  qa: 1000
  types:
    判断题: 0
    填空题: 0
    案例分析题: 0
    简答题: 0
    论述题: 0
    选择题: 0
west:
  ex: 12600
  levels:
    grad:
      ex: 12600
    ug:
      ex: 0
  qa: 1000
  types:
    判断题: 0
    填空题: 0
    案例分析题: 0
    简答题: 0
    论述题: 0
    选择题: 0
经济学院:
  ex: 6600
  qa: 1000
  types:
    判断题: 0
    填空题: 0
    案例分析题: 0
    简答题: 0
    论述题: 0
    选择题: 0
